package main

import (
	"cmp"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"log/slog"
	"net/http"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"sync"
	"time"

	"github.com/gin-gonic/gin"
)

// FilterRule corresponds to one line in a `.duplicacy/filters` file:
// "include" → "+pattern", "exclude" → "-pattern".
type FilterRule struct {
	Position int    `json:"position"`
	Action   string `json:"action"` // "include" | "exclude"
	Pattern  string `json:"pattern"`
}

// FilterSet is a named, scoped collection of FilterRules.
// Pulled from the controller; org and site sets apply across many repos.
type FilterSet struct {
	ID         string       `json:"id"`
	Scope      string       `json:"scope"`       // "org" | "site" | "repo"
	ScopeValue string       `json:"scope_value"` // "" for org, site id for site, repoID for repo
	Name       string       `json:"name"`
	Rules      []FilterRule `json:"rules"`
}

// PerRepoFilters is what we persist locally for repo-specific rules
// (separate from org/site sets which always come from the controller).
type PerRepoFilters struct {
	RepoID    string       `json:"repo_id"`
	Rules     []FilterRule `json:"rules"`
	UpdatedAt time.Time    `json:"updated_at"`
}

// globalFilterCacheFile is the on-disk cache of org+site sets.
type globalFilterCacheFile struct {
	Sets          []FilterSet `json:"sets"`
	LastFetchedAt time.Time   `json:"last_fetched_at"`
}

const autogeneratedHeader = "# AUTOGENERATED by duplicacy-agent-api from controller filter sets\n" +
	"# DO NOT EDIT BY HAND - changes will be overwritten on next sync\n"

type filterCache struct {
	cfg    Config
	client *http.Client
	repos  *repoIndex

	mu          sync.RWMutex
	sets        []FilterSet // org + site sets
	lastFetched time.Time
	cachePath   string
	perRepoDir  string
}

func newFilterCache(cfg Config, client *http.Client, repos *repoIndex) (*filterCache, error) {
	perRepoDir := filepath.Join(cfg.ConfigDir, "per-repo-filters")
	if err := os.MkdirAll(perRepoDir, 0700); err != nil {
		return nil, fmt.Errorf("mkdir per-repo dir: %w", err)
	}
	fc := &filterCache{
		cfg:        cfg,
		client:     client,
		repos:      repos,
		cachePath:  filepath.Join(cfg.ConfigDir, "filter-sets.json"),
		perRepoDir: perRepoDir,
	}
	if err := fc.loadCache(); err != nil {
		slog.Warn("filter cache load failed (starting empty)", "error", err)
	}
	return fc, nil
}

func (f *filterCache) loadCache() error {
	data, err := os.ReadFile(f.cachePath)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}
	var c globalFilterCacheFile
	if err := json.Unmarshal(data, &c); err != nil {
		return fmt.Errorf("parse cache: %w", err)
	}
	f.mu.Lock()
	f.sets = c.Sets
	f.lastFetched = c.LastFetchedAt
	f.mu.Unlock()
	slog.Info("loaded filter cache from disk", "sets", len(c.Sets))
	return nil
}

func (f *filterCache) saveCache() error {
	f.mu.RLock()
	out := globalFilterCacheFile{Sets: f.sets, LastFetchedAt: f.lastFetched}
	f.mu.RUnlock()
	data, err := json.MarshalIndent(out, "", "  ")
	if err != nil {
		return err
	}
	tmp := f.cachePath + ".tmp"
	if err := os.WriteFile(tmp, data, 0600); err != nil {
		return err
	}
	return os.Rename(tmp, f.cachePath)
}

// pull fetches org+site filter sets from the controller.
func (f *filterCache) pull(ctx context.Context) error {
	url := fmt.Sprintf("%s/api/duplicacy/filter-sets?node=%s&site=%s",
		f.cfg.ControlCenterURL, f.cfg.NodeName, f.cfg.SiteID)
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, url, nil)
	if err != nil {
		return err
	}
	resp, err := f.client.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		body, _ := io.ReadAll(resp.Body)
		return fmt.Errorf("HTTP %d: %s", resp.StatusCode, truncate(string(body), 200))
	}
	var body struct {
		Sets []FilterSet `json:"sets"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&body); err != nil {
		return fmt.Errorf("decode: %w", err)
	}
	f.mu.Lock()
	f.sets = body.Sets
	f.lastFetched = time.Now().UTC()
	f.mu.Unlock()
	if err := f.saveCache(); err != nil {
		slog.Warn("save filter cache failed", "error", err)
	}
	slog.Info("filter pull complete", "sets", len(body.Sets))

	// Re-render every discovered repo's .duplicacy/filters since the global rules changed.
	if err := f.renderAll(); err != nil {
		slog.Warn("render-all after pull failed", "error", err)
	}
	return nil
}

// reconcileLoop pulls every 5 min so a missed push notification isn't fatal.
func (f *filterCache) reconcileLoop(ctx context.Context, stop <-chan struct{}) {
	t := time.NewTicker(5 * time.Minute)
	defer t.Stop()
	// best-effort initial pull
	_ = f.pull(ctx)
	for {
		select {
		case <-ctx.Done():
			return
		case <-stop:
			return
		case <-t.C:
			if err := f.pull(ctx); err != nil {
				slog.Warn("filter reconcile pull failed", "error", err)
			}
		}
	}
}

func (f *filterCache) perRepoPath(repoID string) string {
	return filepath.Join(f.perRepoDir, repoID+".json")
}

func (f *filterCache) loadPerRepo(repoID string) (PerRepoFilters, bool, error) {
	data, err := os.ReadFile(f.perRepoPath(repoID))
	if err != nil {
		if os.IsNotExist(err) {
			return PerRepoFilters{RepoID: repoID}, false, nil
		}
		return PerRepoFilters{}, false, err
	}
	var pr PerRepoFilters
	if err := json.Unmarshal(data, &pr); err != nil {
		return PerRepoFilters{}, false, fmt.Errorf("parse per-repo: %w", err)
	}
	return pr, true, nil
}

func (f *filterCache) savePerRepo(pr PerRepoFilters) error {
	pr.UpdatedAt = time.Now().UTC()
	data, err := json.MarshalIndent(pr, "", "  ")
	if err != nil {
		return err
	}
	dest := f.perRepoPath(pr.RepoID)
	tmp := dest + ".tmp"
	if err := os.WriteFile(tmp, data, 0600); err != nil {
		return err
	}
	return os.Rename(tmp, dest)
}

// renderForRepo writes the merged effective filters file at <repo>/.duplicacy/filters.
func (f *filterCache) renderForRepo(repo *Repo) error {
	merged := f.computeMerged(repo.ID, repo.matchRoot())
	dest := filepath.Join(repo.Path, ".duplicacy", "filters")
	tmp := dest + ".tmp"
	if err := os.WriteFile(tmp, []byte(merged), 0600); err != nil {
		return err
	}
	return os.Rename(tmp, dest)
}

// computeMerged builds the file content (used by renderForRepo and the preview
// endpoint).
//
// ORDER IS PER-REPO → SITE → ORG, and that is the opposite of what this function
// used to do. duplicacy's MatchPath (duplicacy_utils.go) walks the pattern list
// and RETURNS on the first '+' or '-' that matches — first match wins, later
// lines never get a look in. Writing org first therefore made per-repo overrides
// dead: any org rule that already matched decided the outcome. The old comment
// here asserted the reverse ("rules later in the file override earlier ones"),
// which is where the bug came from.
//
// matchRoot is the repository root every pattern is anchored against; see
// anchorPattern.
func (f *filterCache) computeMerged(repoID, matchRoot string) string {
	f.mu.RLock()
	sets := append([]FilterSet(nil), f.sets...)
	lastFetched := f.lastFetched
	f.mu.RUnlock()

	var b strings.Builder
	b.WriteString(autogeneratedHeader)
	b.WriteString(fmt.Sprintf("# Last rendered: %s\n", time.Now().UTC().Format(time.RFC3339)))
	b.WriteString(fmt.Sprintf("# Source-of-truth fetched: %s\n", lastFetched.Format(time.RFC3339)))
	b.WriteString("\n")

	// Most specific FIRST, because first match wins.
	pr, _, err := f.loadPerRepo(repoID)
	if err != nil {
		slog.Warn("load per-repo filters failed; rendering without", "error", err, "repo", repoID)
	} else if len(pr.Rules) > 0 {
		b.WriteString("# === REPO: per-repo overrides ===\n")
		writeRules(&b, pr.Rules, matchRoot)
		b.WriteString("\n")
	}

	// Then site, then org — same reason.
	slices.SortStableFunc(sets, func(a, b FilterSet) int {
		return cmp.Or(
			cmp.Compare(scopeOrder(a.Scope), scopeOrder(b.Scope)),
			cmp.Compare(a.Name, b.Name),
		)
	})

	for _, s := range sets {
		// Skip per-repo sets that came from server (we manage those locally).
		if s.Scope == "repo" {
			continue
		}
		b.WriteString(fmt.Sprintf("# === %s%s: %s ===\n",
			strings.ToUpper(s.Scope),
			scopeValueDisplay(s.ScopeValue),
			s.Name))
		writeRules(&b, s.Rules, matchRoot)
		b.WriteString("\n")
	}

	return b.String()
}

// scopeOrder ranks scopes MOST SPECIFIC FIRST, so that a site rule beats an org
// rule under duplicacy's first-match-wins evaluation.
func scopeOrder(s string) int {
	switch s {
	case "site":
		return 0
	case "org":
		return 1
	default:
		return 2
	}
}

func scopeValueDisplay(v string) string {
	if v == "" {
		return ""
	}
	return " (" + v + ")"
}

// anchorPattern converts a stored ABSOLUTE pattern into the repo-relative form
// duplicacy actually matches against, reporting false when the pattern cannot
// apply to this repo at all.
//
// THIS IS THE WHOLE BUG THIS FILE EXISTED WITH. duplicacy builds each entry's
// path in CreateEntryFromFileInfo (duplicacy_entry.go) as `directory + name`,
// starting from "" at the repository root — so what MatchPath sees is always
// RELATIVE and never carries a leading slash. Directories additionally get a
// trailing "/". A stored pattern of
//
//	/home/user/os-images/
//
// is therefore compared against
//
//	os-images/ubuntu/iso-root/sys/bus/workqueue/uevent
//
// and cannot match — the very first byte disagrees. Verified against duplicacy's
// own matcher: the absolute form returns false, and so does the absolute form
// with a wildcard appended. Every rule in the org set was inert on every repo,
// silently, for as long as the feature has existed; the only visible symptom was
// backups walking into directories the operator had excluded.
//
// Patterns are stored absolute on purpose and that stays: one org-scoped set is
// rendered onto repos rooted at /home/user, /srv/containers,
// /mnt/storage and more, so an absolute path is the only spelling that is
// unambiguous across them. Anchoring is a render-time concern because the
// renderer is the only layer that knows which repo it is writing for.
//
// Rules:
//   - already relative (no leading "/") → passed through untouched.
//   - inside this repo → repo-root prefix stripped.
//   - equal to the repo root → dropped. It would strip to "", and an empty
//     pattern matches everything; excluding the entire repository is never what
//     an exclusion list meant to say.
//   - anywhere else → dropped. It can never match, and emitting it only
//     produces a filters file that looks like it is doing something.
//
// A wildcard inside the leading component (e.g. /home/*/x) is not anchorable by
// prefix and so is dropped by the last rule. That is not a regression: duplicacy
// could not have matched it either.
func anchorPattern(pattern, matchRoot string) (string, bool) {
	if pattern == "" {
		return "", false
	}
	if !strings.HasPrefix(pattern, "/") {
		return pattern, true // already repo-relative
	}
	root := strings.TrimSuffix(matchRoot, "/")
	if root == "" || root == "/" {
		// Repo rooted at "/": paths are relative to it, so drop just the leader.
		return strings.TrimPrefix(pattern, "/"), true
	}
	if pattern == root || pattern == root+"/" {
		return "", false
	}
	if rest, ok := strings.CutPrefix(pattern, root+"/"); ok && rest != "" {
		return rest, true
	}
	return "", false
}

// matchRoot is the directory duplicacy resolves entry paths against. That is the
// repository root from preferences (SourcePath) where we have it, falling back
// to the path the agent discovered the repo at.
func (r *Repo) matchRoot() string {
	if r.SourcePath != "" {
		return r.SourcePath
	}
	return r.Path
}

func writeRules(b *strings.Builder, rules []FilterRule, matchRoot string) {
	sorted := append([]FilterRule(nil), rules...)
	slices.SortStableFunc(sorted, func(a, b FilterRule) int { return cmp.Compare(a.Position, b.Position) })
	for _, r := range sorted {
		pattern, ok := anchorPattern(r.Pattern, matchRoot)
		if !ok {
			// Rendered as a comment rather than dropped silently: an operator
			// reading this file needs to see that the rule was considered and
			// does not apply here, not wonder whether the sync is broken.
			b.WriteString("# (not in this repo) ")
			b.WriteString(r.Pattern)
			b.WriteString("\n")
			continue
		}
		prefix := "-"
		if r.Action == "include" {
			prefix = "+"
		}
		b.WriteString(prefix)
		b.WriteString(pattern)
		b.WriteString("\n")
	}
}

// renderAll re-renders every discovered repo. Called after a pull or per-repo edit.
func (f *filterCache) renderAll() error {
	for _, repo := range f.repos.list() {
		if err := f.renderForRepo(repo); err != nil {
			slog.Warn("render filters failed", "error", err, "repo", repo.ID)
		}
	}
	return nil
}

// --- HTTP handlers (override placeholders) ---

func (a *app) handleGetFilters(c *gin.Context) {
	repo, ok := a.repos.get(c.Param("id"))
	if !ok {
		c.JSON(http.StatusNotFound, gin.H{"error": "repo not found"})
		return
	}
	pr, exists, err := a.filters.loadPerRepo(repo.ID)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}
	c.JSON(http.StatusOK, gin.H{
		"repo_id": repo.ID,
		"exists":  exists,
		"rules":   pr.Rules,
		"updated": pr.UpdatedAt,
	})
}

func (a *app) handlePutFilters(c *gin.Context) {
	repo, ok := a.repos.get(c.Param("id"))
	if !ok {
		c.JSON(http.StatusNotFound, gin.H{"error": "repo not found"})
		return
	}
	var body struct {
		Rules []FilterRule `json:"rules"`
	}
	if err := c.ShouldBindJSON(&body); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}
	pr := PerRepoFilters{RepoID: repo.ID, Rules: body.Rules}
	if err := a.filters.savePerRepo(pr); err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}
	if err := a.filters.renderForRepo(repo); err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}
	c.JSON(http.StatusOK, gin.H{"saved": true})
}

func (a *app) handleRenderFilters(c *gin.Context) {
	repo, ok := a.repos.get(c.Param("id"))
	if !ok {
		c.JSON(http.StatusNotFound, gin.H{"error": "repo not found"})
		return
	}
	merged := a.filters.computeMerged(repo.ID, repo.matchRoot())
	c.Data(http.StatusOK, "text/plain; charset=utf-8", []byte(merged))
}

func (a *app) handleGlobalFiltersCache(c *gin.Context) {
	a.filters.mu.RLock()
	defer a.filters.mu.RUnlock()
	c.JSON(http.StatusOK, gin.H{
		"sets":            a.filters.sets,
		"last_fetched_at": a.filters.lastFetched,
	})
}

func (a *app) handleGlobalFiltersRefresh(c *gin.Context) {
	if err := a.filters.pull(c.Request.Context()); err != nil {
		c.JSON(http.StatusBadGateway, gin.H{"error": err.Error()})
		return
	}
	c.JSON(http.StatusOK, gin.H{"refreshed": true})
}
