package main

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"sync"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/rs/zerolog/log"
)

// FilterRule corresponds to one line in a `.duplicacy/filters` file:
// "include" → "+pattern", "exclude" → "-pattern".
type FilterRule struct {
	Position int    `json:"position"`
	Action   string `json:"action"`  // "include" | "exclude"
	Pattern  string `json:"pattern"`
}

// FilterSet is a named, scoped collection of FilterRules.
// Pulled from controller; org and site sets apply across many repos.
type FilterSet struct {
	ID         string       `json:"id"`
	Scope      string       `json:"scope"`       // "org" | "site" | "repo"
	ScopeValue string       `json:"scope_value"` // "" for org, "kd"|"ng" for site, repoID for repo
	Name       string       `json:"name"`
	Rules      []FilterRule `json:"rules"`
}

// PerRepoFilters is what we persist locally for repo-specific rules
// (separate from org/site sets which always come from controller).
type PerRepoFilters struct {
	RepoID    string       `json:"repo_id"`
	Rules     []FilterRule `json:"rules"`
	UpdatedAt time.Time    `json:"updated_at"`
}

// globalFilterCacheFile is the on-disk cache of org+site sets.
type globalFilterCacheFile struct {
	Sets          []FilterSet `json:"sets"`
	LastFetchedAt time.Time   `json:"last_fetched_at"`
}

const autogeneratedHeader = "# AUTOGENERATED by duplicacy-api from controller filter sets\n" +
	"# DO NOT EDIT BY HAND - changes will be overwritten on next sync\n"

type filterCache struct {
	cfg    Config
	client *http.Client
	repos  *repoIndex

	mu              sync.RWMutex
	sets            []FilterSet // org + site sets
	lastFetched     time.Time
	cachePath       string
	perRepoDir      string
}

func newFilterCache(cfg Config, client *http.Client, repos *repoIndex) (*filterCache, error) {
	perRepoDir := filepath.Join(cfg.ConfigDir, "per-repo-filters")
	if err := os.MkdirAll(perRepoDir, 0700); err != nil {
		return nil, fmt.Errorf("mkdir per-repo dir: %w", err)
	}
	fc := &filterCache{
		cfg:        cfg,
		client:     client,
		repos:      repos,
		cachePath:  filepath.Join(cfg.ConfigDir, "filter-sets.json"),
		perRepoDir: perRepoDir,
	}
	if err := fc.loadCache(); err != nil {
		log.Warn().Err(err).Msg("filter cache load failed (starting empty)")
	}
	return fc, nil
}

func (f *filterCache) loadCache() error {
	data, err := os.ReadFile(f.cachePath)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}
	var c globalFilterCacheFile
	if err := json.Unmarshal(data, &c); err != nil {
		return fmt.Errorf("parse cache: %w", err)
	}
	f.mu.Lock()
	f.sets = c.Sets
	f.lastFetched = c.LastFetchedAt
	f.mu.Unlock()
	log.Info().Int("sets", len(c.Sets)).Msg("loaded filter cache from disk")
	return nil
}

func (f *filterCache) saveCache() error {
	f.mu.RLock()
	out := globalFilterCacheFile{Sets: f.sets, LastFetchedAt: f.lastFetched}
	f.mu.RUnlock()
	data, err := json.MarshalIndent(out, "", "  ")
	if err != nil {
		return err
	}
	tmp := f.cachePath + ".tmp"
	if err := os.WriteFile(tmp, data, 0600); err != nil {
		return err
	}
	return os.Rename(tmp, f.cachePath)
}

// pull fetches org+site filter sets from controller.
func (f *filterCache) pull(ctx context.Context) error {
	url := fmt.Sprintf("%s/api/duplicacy/filter-sets?node=%s&site=%s",
		f.cfg.ControlCenterURL, f.cfg.NodeName, f.cfg.SiteID)
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, url, nil)
	if err != nil {
		return err
	}
	resp, err := f.client.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		body, _ := io.ReadAll(resp.Body)
		return fmt.Errorf("HTTP %d: %s", resp.StatusCode, truncate(string(body), 200))
	}
	var body struct {
		Sets []FilterSet `json:"sets"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&body); err != nil {
		return fmt.Errorf("decode: %w", err)
	}
	f.mu.Lock()
	f.sets = body.Sets
	f.lastFetched = time.Now().UTC()
	f.mu.Unlock()
	if err := f.saveCache(); err != nil {
		log.Warn().Err(err).Msg("save filter cache failed")
	}
	log.Info().Int("sets", len(body.Sets)).Msg("filter pull complete")

	// Re-render every discovered repo's .duplicacy/filters since the global rules changed.
	if err := f.renderAll(); err != nil {
		log.Warn().Err(err).Msg("render-all after pull failed")
	}
	return nil
}

// reconcileLoop pulls every 5 min so a missed push notification isn't fatal.
func (f *filterCache) reconcileLoop(ctx context.Context, stop <-chan struct{}) {
	t := time.NewTicker(5 * time.Minute)
	defer t.Stop()
	// best-effort initial pull
	_ = f.pull(ctx)
	for {
		select {
		case <-ctx.Done():
			return
		case <-stop:
			return
		case <-t.C:
			if err := f.pull(ctx); err != nil {
				log.Warn().Err(err).Msg("filter reconcile pull failed")
			}
		}
	}
}

func (f *filterCache) perRepoPath(repoID string) string {
	return filepath.Join(f.perRepoDir, repoID+".json")
}

func (f *filterCache) loadPerRepo(repoID string) (PerRepoFilters, bool, error) {
	data, err := os.ReadFile(f.perRepoPath(repoID))
	if err != nil {
		if os.IsNotExist(err) {
			return PerRepoFilters{RepoID: repoID}, false, nil
		}
		return PerRepoFilters{}, false, err
	}
	var pr PerRepoFilters
	if err := json.Unmarshal(data, &pr); err != nil {
		return PerRepoFilters{}, false, fmt.Errorf("parse per-repo: %w", err)
	}
	return pr, true, nil
}

func (f *filterCache) savePerRepo(pr PerRepoFilters) error {
	pr.UpdatedAt = time.Now().UTC()
	data, err := json.MarshalIndent(pr, "", "  ")
	if err != nil {
		return err
	}
	dest := f.perRepoPath(pr.RepoID)
	tmp := dest + ".tmp"
	if err := os.WriteFile(tmp, data, 0600); err != nil {
		return err
	}
	return os.Rename(tmp, dest)
}

// renderForRepo writes the merged effective filters file at <repo>/.duplicacy/filters.
// Order: org → site → per-repo. Rules later in the file override earlier ones in duplicacy semantics.
func (f *filterCache) renderForRepo(repo *Repo) error {
	merged := f.computeMerged(repo.ID)
	dest := filepath.Join(repo.Path, ".duplicacy", "filters")
	tmp := dest + ".tmp"
	if err := os.WriteFile(tmp, []byte(merged), 0600); err != nil {
		return err
	}
	return os.Rename(tmp, dest)
}

// computeMerged builds the file content (used by renderForRepo and the preview endpoint).
func (f *filterCache) computeMerged(repoID string) string {
	f.mu.RLock()
	sets := append([]FilterSet(nil), f.sets...)
	lastFetched := f.lastFetched
	f.mu.RUnlock()

	var b strings.Builder
	b.WriteString(autogeneratedHeader)
	b.WriteString(fmt.Sprintf("# Last rendered: %s\n", time.Now().UTC().Format(time.RFC3339)))
	b.WriteString(fmt.Sprintf("# Source-of-truth fetched: %s\n", lastFetched.Format(time.RFC3339)))
	b.WriteString("\n")

	// Sort sets so org first, then site, deterministic by name within each.
	sort.SliceStable(sets, func(i, j int) bool {
		if sets[i].Scope != sets[j].Scope {
			return scopeOrder(sets[i].Scope) < scopeOrder(sets[j].Scope)
		}
		return sets[i].Name < sets[j].Name
	})

	for _, s := range sets {
		// Skip per-repo sets that came from server (we manage those locally).
		if s.Scope == "repo" {
			continue
		}
		b.WriteString(fmt.Sprintf("# === %s%s: %s ===\n",
			strings.ToUpper(s.Scope),
			scopeValueDisplay(s.ScopeValue),
			s.Name))
		writeRules(&b, s.Rules)
		b.WriteString("\n")
	}

	pr, _, err := f.loadPerRepo(repoID)
	if err != nil {
		log.Warn().Err(err).Str("repo", repoID).Msg("load per-repo filters failed; rendering without")
	} else if len(pr.Rules) > 0 {
		b.WriteString("# === REPO: per-repo overrides ===\n")
		writeRules(&b, pr.Rules)
	}
	return b.String()
}

func scopeOrder(s string) int {
	switch s {
	case "org":
		return 0
	case "site":
		return 1
	default:
		return 2
	}
}

func scopeValueDisplay(v string) string {
	if v == "" {
		return ""
	}
	return " (" + v + ")"
}

func writeRules(b *strings.Builder, rules []FilterRule) {
	sorted := append([]FilterRule(nil), rules...)
	sort.SliceStable(sorted, func(i, j int) bool { return sorted[i].Position < sorted[j].Position })
	for _, r := range sorted {
		prefix := "-"
		if r.Action == "include" {
			prefix = "+"
		}
		b.WriteString(prefix)
		b.WriteString(r.Pattern)
		b.WriteString("\n")
	}
}

// renderAll re-renders every discovered repo. Called after a pull or per-repo edit.
func (f *filterCache) renderAll() error {
	for _, repo := range f.repos.list() {
		if err := f.renderForRepo(repo); err != nil {
			log.Warn().Err(err).Str("repo", repo.ID).Msg("render filters failed")
		}
	}
	return nil
}

// --- HTTP handlers (override placeholders) ---

func (a *app) handleGetFilters(c *gin.Context) {
	repo, ok := a.repos.get(c.Param("id"))
	if !ok {
		c.JSON(http.StatusNotFound, gin.H{"error": "repo not found"})
		return
	}
	pr, exists, err := a.filters.loadPerRepo(repo.ID)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}
	c.JSON(http.StatusOK, gin.H{
		"repo_id":   repo.ID,
		"exists":    exists,
		"rules":     pr.Rules,
		"updated":   pr.UpdatedAt,
	})
}

func (a *app) handlePutFilters(c *gin.Context) {
	repo, ok := a.repos.get(c.Param("id"))
	if !ok {
		c.JSON(http.StatusNotFound, gin.H{"error": "repo not found"})
		return
	}
	var body struct {
		Rules []FilterRule `json:"rules"`
	}
	if err := c.ShouldBindJSON(&body); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}
	pr := PerRepoFilters{RepoID: repo.ID, Rules: body.Rules}
	if err := a.filters.savePerRepo(pr); err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}
	if err := a.filters.renderForRepo(repo); err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}
	c.JSON(http.StatusOK, gin.H{"saved": true})
}

func (a *app) handleRenderFilters(c *gin.Context) {
	repo, ok := a.repos.get(c.Param("id"))
	if !ok {
		c.JSON(http.StatusNotFound, gin.H{"error": "repo not found"})
		return
	}
	merged := a.filters.computeMerged(repo.ID)
	c.Data(http.StatusOK, "text/plain; charset=utf-8", []byte(merged))
}

func (a *app) handleGlobalFiltersCache(c *gin.Context) {
	a.filters.mu.RLock()
	defer a.filters.mu.RUnlock()
	c.JSON(http.StatusOK, gin.H{
		"sets":            a.filters.sets,
		"last_fetched_at": a.filters.lastFetched,
	})
}

func (a *app) handleGlobalFiltersRefresh(c *gin.Context) {
	if err := a.filters.pull(c.Request.Context()); err != nil {
		c.JSON(http.StatusBadGateway, gin.H{"error": err.Error()})
		return
	}
	c.JSON(http.StatusOK, gin.H{"refreshed": true})
}
